name: Python

on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      WORKON_HOME: cache/venv
      PIPENV_CACHE_DIR: cache/pipenv
      OSMNX_CACHE_DIR: cache/osmnx
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9.2"  # TODO, use version from .tool-versions
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: cache
        key: ${{ runner.os }}-cache-${{ hashFiles('Pipfile.lock') }}
        restore-keys: ${{ runner.os }}-cache-
    - name: Install dependencies
      run: pip install pipenv && pipenv sync -d
    - name: Check formatting
      run: pipenv run format --check
    - name: Linting
      run: pipenv run lint
    - name: Run tests
      run: pipenv run test -v --cov=registered --cov-fail-under=74
